image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
tasks:
- command: |
    mkdir -p /home/gitpod/.android
    touch /home/gitpod/.android/repositories.cfg
    export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$PATH
    /home/gitpod/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
vscode:
  extensions:
    - Dart-Code.flutter@3.5.0:/kOacEWdiDRLyN/idUiM4A==